/* empty css                      */import{a as w,S as v,i}from"./assets/vendor-D1-p2jAf.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const P="50667452-1c0751a5fadad2372abc27daa",B="https://pixabay.com/api/",I=15;async function g(t,r=1){const n={key:P,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:I};try{return(await w.get(B,{params:n})).data}catch{throw new Error("Failed to fetch images")}}let d;function h(t){const r=document.getElementById("gallery"),n=t.map(({webformatURL:s,largeImageURL:e,tags:o,likes:a,views:b,comments:L,downloads:E})=>`
    <li class="photo-card">
      <a href="${e}">
        <img src="${s}" alt="${o}" loading="lazy" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${a}</p>
        <p><b>Views:</b> ${b}</p>
        <p><b>Comments:</b> ${L}</p>
        <p><b>Downloads:</b> ${E}</p>
      </div>
    </li>
  `).join("");r.insertAdjacentHTML("beforeend",n),d?d.refresh():d=new v("#gallery a")}function M(){document.getElementById("gallery").innerHTML=""}function c(t){document.getElementById("loader").classList.toggle("hidden",!t)}const S=document.getElementById("search-form"),m=document.getElementById("load-more");let l=1,u="",f=0;S.addEventListener("submit",$);m.addEventListener("click",O);async function $(t){t.preventDefault();const r=t.currentTarget.query.value.trim();if(!r){i.warning({title:"Warning",message:"Please enter a search term."});return}u=r,l=1,M(),y(),c(!0);try{const{hits:n,totalHits:s}=await g(u,l);if(f=s,n.length===0){i.error({title:"No results",message:"No images found."});return}h(n),n.length<f&&p()}catch(n){i.error({title:"Error",message:n.message})}finally{c(!1)}}async function O(){l++,c(!0),y();try{const{hits:t}=await g(u,l);h(t),q();const r=Math.ceil(f/15);l<r?p():i.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})}catch(t){i.error({title:"Error",message:t.message})}finally{c(!1)}}function p(){m.classList.remove("hidden")}function y(){m.classList.add("hidden")}function q(){const{height:t}=document.querySelector(".gallery li").getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
